<?php

/**
 * Implementation of hook_menu().
 */
function class_subject_search_menu() {
	
	$items = array();
	$items['get-subjects'] = array(
    'page callback' => 'get_subjects',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
	
	
  return $items;
	}

/**
 * Implements hook_block_info().
 */
function class_subject_search_block_info() {
  $blocks = array();
  $blocks['subject_search_block'] = array(
    'info' => t('Class and subject search'),
  );
  
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function class_subject_search_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'subject_search_block':
      $block['subject'] = '';
      $block['content'] = _class_subject_search_add_content();
      break;
    
  }

  return $block;
}

function _class_subject_search_add_content(){
	global $base_url;
	$query = db_select('node','n');
	$query->condition('n.type','book_lessons');
	$query->condition('n.status','1');
	$query->fields('n', array('nid'));
	$nid_array = $query->execute()->fetchCol();
	
	$book_lesson_node_load = node_load_multiple($nid_array);
	
	
	
	foreach($book_lesson_node_load as $title){
		$class_title[] = $title->title;
		$node_ids[] = $title->nid;
		}
		
		$nid_class_array = array_combine($node_ids,$class_title );
	    //echo'<pre>';
	    //print_r($cc);
	
	
	
	$value = '';
	
	$value .=  '<div class="search-screen">';
	$value .=  '<form name="subject_class_search" id="search-target" action="' . $base_url .'" method="GET">';
	$value .=  '<div class = "subject-select">';
	$value .=  '<select name="classes" id="ClasSelect"><option value="">Select Class</option>';
	foreach($nid_class_array as $nid => $class_names){
	$value .=  '<option value="'.$nid.'">'.$class_names.'</option>';
	}
	$value .=  '</select>';
	$value .=  '<select name="subject" id="SubjSelect" class="xyzzz" multiple>';      
	//$value .=  '<option value="">Select Subject</option>';
	$value .=  '</select>';
	$value .=  '</div>';
	$value .=  '<div class="search_button"><input class="button" id="cls-srch-btn" type=submit value="Search"></div>';
	//$value .=  '<div class="search_reset"><a class="button" href="' . $base_url . '">Reset</a></div>';
	$value .=  '</form>';
	$value .=  '</div>';          
			
	            
	return $value;
}




function get_subjects() {
	
	$nid = $_GET['nid'];
	$node_object = node_load($nid);
	$lesson_ids = $node_object->field_lessons['und'];
	foreach($lesson_ids as $product){
	$prod_id_array[] = $product;
    }
    
    
    
    //display($ss);
    
    
    foreach($prod_id_array as $prod_names){
		$prod_list[] = $prod_names['product_id'];
		}
	
	
	
	$subjects_products_load = commerce_product_load_multiple($prod_list);
	
	
	foreach($subjects_products_load as $key => $subjects){
		$subjects_title[$key] = $subjects->title;
		};
	  //display($subjects_title);
	//drupal_json_encode($prod_list) 
	drupal_json_output($subjects_title);
	
	//drupal_exit();
	exit();
	
	
}
