<?php
/*
 * Implements hook_menu()
 * for Hire Teacher 
 */
function hire_teacher_menu() {
	$items['hire-teacher-go-to-checkout'] = array(
			'title' => 'Hire Teacher Go to Checkout',
			'page callback' => 'hire_teacher_go_to_checkout',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);
	
	$items['teachers-professional-training-go-to-checkout'] = array(
			'page callback' => 'teachers_professional_training_go_to_checkout',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);

	return $items;
}

function hire_teacher_go_to_checkout( $product_id = 132 ) {
	global $user;
	$uid = $user->uid;

	$_SESSION['hire_teacher'] = 'hire-teacher';

	$order = commerce_cart_order_load($uid);

	if( $order != FALSE ) {
		commerce_cart_order_empty( $order );
	}

	$line_item = commerce_product_line_item_new(commerce_product_load($product_id));
	commerce_cart_product_add($uid,$line_item);
	drupal_goto('checkout');
}

/**
 * for Teachers Professional Training
 */
function teachers_professional_training_go_to_checkout( $product_id = 133 ) {
	global $user;
	$uid = $user->uid;

	$_SESSION['teachers_professional_training'] = 'teachers_professional_training';

	$order = commerce_cart_order_load($uid);

	if( $order != FALSE ) {
		commerce_cart_order_empty( $order );
	}

	$line_item = commerce_product_line_item_new(commerce_product_load($product_id));
	commerce_cart_product_add($uid,$line_item);
	drupal_goto('checkout');
}


/*
 * Implements hook_form_alter
 */
function hire_teacher_form_commerce_checkout_form_complete_alter( &$form, &$form_state ) {

	if( array_key_exists( 'hire_teacher', $_SESSION ) ) {
		global $user;
		$uid = $user->uid;

		$form['checkout_completion_message']['message']['#markup'] = "Thanks for making payment.<br>
		Please click here to go back to <a href='$base_url/hire-teacher-listing'>Hire teacher</a> listing page";

		$path_to_mpdf = drupal_get_path( 'module', 'pdf_using_mpdf') . '/mpdf60/mpdf.php';
		$path_to_quiz_do_lessons = drupal_get_path( 'module', 'quiz_do_lessons');

		include("$path_to_mpdf");

		$html = '<!DOCTYPE html>
					<html lang="en">
					<head>
					  <meta charset="utf-8">
					  <meta http-equiv="X-UA-Compatible" content="IE=edge">
					  <meta name="viewport" content="width=device-width, initial-scale=1">
					  <!-- The above 3 meta tags must come first in the head; any other head content must come after these tags -->
					  <title>DoLessons</title>
		
					</head>
					    <body style="margin:0;padding:0;">
		
					      <!--header section-->
					      <header class="p-top" style="width:100%;float:left; padding: 10px 0;">
					        <div class="container" style="max-width:800px;margin:0 auto;">
					           <h1 style="display:inline-block;float:left;margin:0;line-height:100%;"><a class="logo" href="#" style="display:block;"><img src="'.$path_to_quiz_do_lessons.'/img/logo.png" alt="logo"></a></h1>

					        <h2 style="float:right; margin-top: 0px;">Payment Recieved</h2>


					     <div class="p-user-details" style="width:100%;float:left;margin:0px;">
					       <h4>Hello <span>'. $user->name .'</span></h4>
					     </div>

					  </div>

					      </header>
					      <!--end header section-->
					      <section>
					     <div class="container" style="max-width:800px;margin:0 auto;">
					       <div class="p-payinfo" style="width:100%;float:left;margin:0;">
					      <p style="font-size: 16px; line-height:20px;">This is to acknowledge your N50, 000 commitment fee payment for Teachers Recruitment. We are super excited about your decision to contract Dolessons to hire quality teachers for your organization. </p>

					   <p>As a smart, experience and innovative educational platform, we have adequate technical and logical expertise to comb the mob of ‘I can Teach’ crowd of applicants to getting you the best professionals with passion for education and undying zeal to helping students develop their study skills via excellent teaching methodologies. We shall update you with 72 hours after analyzing your request.</p>
					    </div>
					    <div class="p-thank-info" style="width:100%;float:left;margin-top: 10px; padding-left: 40px;">
					      <div class="container" style="max-width:800px;margin:0 auto;">
					         <h4 style="display:block; margin-bottom: 10px;">Thank you for choosing DoLessons</h4>
					       <p style="font-size: 15px; line-height:20px;">Martins Fidelis<br>
					                      <span style="display:block;width:100%;">For: DoLessons’ Team</span>
					    </p>
					   </div>
					    </div>
					     </div>
					      </section>
					      <!--footer-->
					      <footer>
					        <div class="p-copyright" style="width:100%;float:left;padding:40px 0;background:#18294d;color:#fff;margin-top:40px;">
					          <div class="container" style="max-width:800px;margin:0 auto;">
					      <div class="p-footer-nav" style="float:left;margin:0;padding:0;">
				            <a href="'. $base_url .'/node/12" title="Privacy  Policy" style="text-decoration:none;font-size: 13px; line-height:20px;font-weight:bold;color:#fff;display:inline-block;margin-right:10px;">Privacy Policy</a>
					        <a href="'. $base_url .'/node/13" title="Terms of Use" style="text-decoration:none;font-size: 13px; line-height:20px;font-weight:bold;color:#fff; display:inline-block;margin-right:10px;">Terms of Use</a>
					        <a href="#" title="FAQ" style="text-decoration:none;font-size: 13px; line-height:20px;font-weight:bold;color:#fff;display:inline-block;margin-right:10px;">FAQ</a>
					        <a href="#" title="Submit Ticket" style="text-decoration:none;font-size: 13px; line-height:20px;font-weight:bold;color:#fff;display:inline-block;margin-right:10px;">Submit Ticket</a>
					        <a href="'. $base_url .'/contact-us" title="Contact Us" style="text-decoration:none;font-size: 13px; line-height:20px;font-weight:bold;color:#fff;display:inline-block;margin-right:10px;">Contact Us</a>

       

					            <a href="https://www.facebook.com/dolessons" style="list-style:none;display:inline-block;margin-left:50px;"><img src="'.$path_to_quiz_do_lessons.'/img/facebook-icon.png" alt="facebook-icon"></a>
					            <a href="https://twitter.com/dolessons" style="list-style:none;display:inline-block;margin-right:10px;"><img src="'.$path_to_quiz_do_lessons.'/img/twitter-icon.png" alt="twitter-icon"></a>
					            <a href="#" style="list-style:none;display:inline-block;margin-right:10px;"><img src="'.$path_to_quiz_do_lessons.'/img/g-icon.png" alt="g-icon"></a>
					            <a href="#" style="list-style:none;display:inline-block;margin-right:10px;"><img src="'.$path_to_quiz_do_lessons.'/img/you-tube.png" alt="you-tube"></a>
					            <a href="#" style="list-style:none;display:inline-block;margin-right:10px;"><img src="'.$path_to_quiz_do_lessons.'/img/linkd.png" alt="linkd"></a>
					            <a href="#" style="list-style:none;display:inline-block;margin-right:10px;"><img src="'.$path_to_quiz_do_lessons.'/img/insta-icon.png" alt="insta-icon"></a>


					    </div>




					            <small style="display:block;width:100%;float:left;margin:20px 0 0;">©Copyright 2015 DoLessons. All Rights Reserved</small>
					          </div>
					        </div>
					      </footer>
					      <!--end footer-->


					    </body>
					</html>';
		// Setup PDF
		$mpdf = new mPDF('utf-8', 'A4-L'); // New PDF object with encoding & page size
		$mpdf->setAutoTopMargin = 'stretch'; // Set pdf top margin to stretch to avoid content overlapping
		$mpdf->setAutoBottomMargin = 'stretch'; // Set pdf bottom margin to stretch to avoid content overlapping
		// PDF header content
		//	$mpdf->SetHTMLHeader('<div class="pdf-header"><img class="left" src="assets/img/pdf_header.png"/></div>');
		// PDF footer content
		//$mpdf->SetHTMLFooter('<div class="pdf-footer"> <a href="http://www.lubus.in">www.lubus.in</a></div>');

		// 		$mpdf->WriteHTML($stylesheet,1); // Writing style to pdf
		$mpdf->WriteHTML($html); // Writing html to pdf
		// FOR EMAIL
		$content = $mpdf->Output('', 'S'); // Saving pdf to attach to email
		$content = chunk_split(base64_encode($content));

		$site_email = variable_get('site_mail', '');

		// Email settings
		$mailto = $user->mail;
		$from_name = $user->name;
		$from_mail = $site_email;
		$replyto = $site_email;
		$uid = md5(uniqid(time()));
		$subject = 'Recruitment Letter';
		$message = 'Thanks for making payment. Download the attached pdf.';
		$filename = 'RecruitmentLetter.pdf';
		$header = "From: ".$from_name." <".$from_mail.">\r\n";
		$header .= "Reply-To: ".$replyto."\r\n";
		$header .= "MIME-Version: 1.0\r\n";
		$header .= "Content-Type: multipart/mixed; boundary=\"".$uid."\"\r\n\r\n";
		$header .= "This is a multi-part message in MIME format.\r\n";
		$header .= "--".$uid."\r\n";
		$header .= "Content-type:text/plain; charset=iso-8859-1\r\n";
		$header .= "Content-Transfer-Encoding: 7bit\r\n\r\n";
		$header .= $message."\r\n\r\n";
		$header .= "--".$uid."\r\n";
		$header .= "Content-Type: application/pdf; name=\"".$filename."\"\r\n";
		$header .= "Content-Transfer-Encoding: base64\r\n";
		$header .= "Content-Disposition: attachment; filename=\"".$filename."\"\r\n\r\n";
		$header .= $content."\r\n\r\n";
		$header .= "--".$uid."--";
		$is_sent = mail($mailto, $subject, "", $header);

		unset( $_SESSION['hire_teacher'] );

	}
}


