<?php
/**
 * Implements hook_init().
 */
function olw_form_init() {
  drupal_add_js(drupal_get_path("module","olw_form").'/olw_form.js');
  drupal_add_js( array( 'basepath' => base_path() ), 'setting' );
  //drupal_add_css(drupal_get_path("module","olw_form").'/olw_form.css');
}
/**
 * Implementation of hook_form_alter()
 */
function olw_form_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  global $base_path;
    if($form_id == 'user_register_form'){
      $form['field_first_name']['#weight'] = -100;
      $form['field_last_name']['#weight'] = -99;
      $form['field_gender']['#weight'] = -3;
      $form['field_user_date_of_birth']['#weight'] = -2;
      $path = current_path();
    /*  if($path == 'teacher/register'){
          $form['actions']['submit']['#value']=t('Submit');
          }*/
      if($path == 'student/register' || $path == 'tutor/register' || $path == 'seller/register' || $path == 'orders/register'){
            
            $form['next'] = array(
            '#type' => 'button',
            '#value' => 'Next >>',
            '#prefix' => '<div class="register-next">',
            '#suffix' => '</div>',
            '#attributes' => array(
             'class' => array('btn-default-global')),
            '#weight' => '0',
            );
            $form['actions']['submit']['#value']=t('Sign-up');
            $form['captcha']['#weight']='5';
          

        }
        $form['account']['mail']['#title']=t('Email'); 
        $form['account']['mail']['#description']=''; 
    }
    if($form_id == 'user_login'){
        $form['name']['#title'] = t("Email Address");
        $form['subs_markup']=array(
        '#markup' => "<p><a href='".$base_path."user/password'>Forget password</a></p>",'#weight'=>'5');
        $form['actions']['submit']['#value'] = t("Submit"); 

        $form['actions']['sub_markup']=array(
        '#markup' => "<p>New to do lesson ? <a href='".$base_path."student/register'>sign up now</a></p>",'#weight'=>'5');
        $form['name']['#prefix'] = '<div id="user_login_form">';
        $form['actions']['#suffix'] = '</div>';
  }
 }

 function olw_form_menu() {
   $items = array();

   $items['register'] = array(
        'title' => 'User Signup',
        'page callback' => 'custom_signup',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
   return $items;
 }
/**
 * Implementation of hook_menu_local_tasks_alter()
 */
function olw_form_menu_local_tasks_alter(&$data, $router_item, $root_path) {
    global $user;
    $uid = $user->uid;
    $path = current_path();
   if ( !($uid) && ($path == 'user')) {
    
    unset($data['tabs'][0]['output'][0]);
    $data['tabs'][0]['output'][1]['#link']['title'] = 'User Login';
    unset($data['tabs'][0]['output'][2]);
    
   }
   if ( !($uid) && ($path == 'user/login')) {
    
    unset($data['tabs'][0]['output'][0]);
    $data['tabs'][0]['output'][1]['#link']['title'] = 'User Login';
    unset($data['tabs'][0]['output'][2]);
    
   }
    if ( !($uid) && ($path == 'student/register')) {
    
    unset($data['tabs'][0]['output'][0]);
    unset($data['tabs'][0]['output'][1]);
    unset($data['tabs'][0]['output'][2]);
    
   }
    if ( !($uid) && ($path == 'tutor/register')) {
    
    unset($data['tabs'][0]['output'][0]);
    unset($data['tabs'][0]['output'][1]);
    unset($data['tabs'][0]['output'][2]);
    
   }
   if ( !($uid) && ($path == 'seller/register')) {
    
    unset($data['tabs'][0]['output'][0]);
    unset($data['tabs'][0]['output'][1]);
    unset($data['tabs'][0]['output'][2]);
    
   }
    if ( !($uid) && ( ($path == 'user/password') || ($path == 'orders/register')) ) {
    
    unset($data['tabs'][0]['output'][0]);
    unset($data['tabs'][0]['output'][1]);
    unset($data['tabs'][0]['output'][2]);
    
   }
}


function custom_signup(){
 // echo "hello";

     $form['selectUser'] = array(
       '#type' => 'select',
       '#title' => t('Sign-up as:'),
       '#options' => array(
         'none' => t('-Select User Type-'),
         'student' => t('Student'),
         'tutor' => t('Tutor'),
         'seller' => t('Seller'),
         'others' => t('Others'),
       ),
       '#default_value' => $category['none'],
       '#description' => t('Select the User type with which you want to Signup'),
        '#attributes' => array(
        'class' => array('signup-custom')),
        );

    return $form;

}



