<?php

/**
 * Implements hook_menu().
 */
function dolcard_menu() {
	$items['dolcard'] = array(
			'title' => 'DolCard',
			'page callback' => 'dolcard',
			'access callback' => TRUE,
			//'access callback' => 'example_user_has_role',
	);
	return $items;
}

function dolcard() {
	global $base_url;
	global $user;
	
	$content = '';
	$uid = $user->uid;
	
	global $base_path;
	
	$path = $_SERVER['DOCUMENT_ROOT'];
	
	$font = "$path$base_path" . "sites/all/themes/custom/bootstrap_olw/fonts/arial.ttf";
	
	$logo_file_path = "$base_url/sites/all/themes/custom/bootstrap_olw/images/logo.png";
	$logo = imagecreatefrompng($logo_file_path);
	
	$result = db_select('node', 'n')
	->fields('n')
	->condition('uid', $uid,'=')
	->condition('type', 'teacher_application_form','=')
	->execute()
	->fetchAssoc();
	
	if( $result ) {
			
		$teacher_node = node_load( $result['nid'] );
	
		$profile_image = $teacher_node->field_teacher_user_profile_image['und'][0]['uri'];
		$image_type = $teacher_node->field_teacher_user_profile_image['und'][0]['filemime'];
	
		$profile_img = drupal_realpath( $profile_image );
		
// 		$imgSmall = image_load($profile_img);
// 		image_resize($imgSmall, 150, 150);
// 		image_save($imgSmall,$profile_img);
	
		if( 'image/jpeg' == $image_type ) {
			$profile = imagecreatefromjpeg($profile_img);
		}
		if( 'image/png' == $image_type ) {
			$profile = imagecreatefrompng($profile_img);
		}
		if( 'image/gif' == $image_type ) {
			$profile = imagecreatefromgif($profile_img);
		}
			
		putenv('GDFONTPATH=' . realpath('.'));
		$im = @imagecreate(600, 650) or die("Cannot Initialize new GD image stream");
		$background_color = imagecolorallocate($im,  21, 67, 96);
		$red = imagecolorallocate($im, 255, 0, 0);
		$white = imagecolorallocate($im, 255, 255, 255);
	
		imagefilledrectangle ($im, 0,  300, 600, 100, $white);
	
		imageline ($im,   0,  360, 600, 360, $white);
		imageline ($im,   0,  410, 600, 410, $white);
		imageline ($im,   0,  550, 600, 550, $white);
		imageline ($im,   0,  600, 600, 600, $white);
	
	
		$text = 'DolCard';
		$teacher_name = "Teacher's Name                :   ";
		$teacher_name .= isset( $teacher_node->field_teacher_name['und'][0]['value'] ) ? $teacher_node->field_teacher_name['und'][0]['value'] : '';
	
		$arr_qualification = isset( $teacher_node->field_teacher_badge_hidden['und'] ) ? $teacher_node->field_teacher_badge_hidden['und'] : '';
		$qualification_teacher = '';
		$i = count( $arr_qualification );
	
		if( $i >= 1 ) {
			foreach( $arr_qualification as $q ) {
				$qualification = taxonomy_term_load($q['tid']);
				$qualification_teacher .= $qualification->name;
				if( $i > 1 ) {
					$qualification_teacher .= ', ';
				}
				$i--;
			}
				
			$qualification_of_teacher = "Qualification                      :   $qualification_teacher";
				
			$teacher_address1 = 'Address                            :   ';
			$teacher_address1 .= isset( $teacher_node->field_teacher_res_address_num['und'][0]['value'] ) ? $teacher_node->field_teacher_res_address_num['und'][0]['value'] : '';
			$teacher_address1 .= ', ';
			$teacher_address1 .= isset( $teacher_node->field_teacher_street['und'][0]['value'] ) ? $teacher_node->field_teacher_street['und'][0]['value'] : '';
			$teacher_address2 = isset( $teacher_node->field_teacher_bus_stop['und'][0]['value'] ) ? $teacher_node->field_teacher_bus_stop['und'][0]['value'] : '';
				
			$teacher_state_tid = $teacher_node->field_teacher_state_of_res['und'][0]['tid'];
				
			$term = taxonomy_term_load($teacher_state_tid);
			$name = $term->name;
				
			$teacher_address2 .= ', ';
			$teacher_address2 .= $name;
				
			$result = db_select('twilio_otp', 't')
			->fields('t')
			->condition('uid', $uid,'=')
			->execute()
			->fetchAssoc();
				
			$mobile_number = '';
			$country_code = '';
			if( $result ) {
				$mobile_number = $result['mobile_number'];
				$country_code = $result['country_code'];
			}
			$phone_number = "Phone Number                 :   $country_code - $mobile_number";
				
			$arr_user = db_select('users', 'u')
			->fields('u')
			->condition('uid', $uid,'=')
			->execute()
			->fetchAssoc();
				
			$security_number = $uid;
			if( $arr_user ) {
				$timestamp = $arr_user['created'];
				$security_number .= date("my", $timestamp);
			}
				
			$dolessons_number = "Teacher Id                        :   $security_number";
	
			imagettftext($im, 24, 0, 240, 80, $white, $font, $text);
			imagettftext($im, 16, 0, 40, 350, $white, $font, $teacher_name);
			imagettftext($im, 16, 0, 40, 400, $white, $font, $qualification_of_teacher);
			imagettftext($im, 16, 0, 40, 450, $white, $font, $teacher_address1);
			imagettftext($im, 16, 0, 340, 500, $white, $font, $teacher_address2);
			imagettftext($im, 16, 0, 40, 585, $white, $font, $phone_number);
			imagettftext($im, 16, 0, 40, 635, $white, $font, $dolessons_number);
				
			imagecopy($im, $logo, 10, 20, 0, 0, 150, 150);

			$profile = imagescale($profile, 150, 150);
			imagecopy( $im, $profile, 220, 130, 0, 0, 150, 150 );

			imagepng($im,"$path$base_path" . "sites/default/files/DolCard/Dolcard_$uid.png");
			imagedestroy($im);
			
			$content = "<img src='$base_url/sites/default/files/DolCard/Dolcard_$uid.png'>";
			
		} else {
			drupal_set_message( 'Please give your exam first.', 'warning' );
		}
	} else {
		drupal_set_message( 'Please fill Teacher\'s application form.', 'warning' );
	}
	
	return $content;
}
