<?php

/*
 * Implementation of hook_form_alter()
 */
 
 function student_unique_id_form_alter(&$form, &$form_state, $form_id){
	 if ($form_id == 'user_register_form') {
		 

		 //$form['#submit'][] = 'computed_field_field_student_unique_id_compute';    

		 //echo'<pre>';
		 //print_r($form);
 }
	 
 }

//function computed_field_field_student_unique_id_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items){
	
//}
