<?php

/*
 * Implements hook_form_alter()
 */
function dashboard_redirect_form_user_login_alter( &$form, &$form_state ) {

	$form['#submit'][] = 'dashboard_redirect_user_login_submit';
}

function dashboard_redirect_user_login_submit($form, &$form_state) {
	
	global $user;
	global $base_url;
	
	$user_roles = $user->roles;
	
	$redirect = 'home';
	foreach( $user_roles as $key => $user_role ) {
		
		if( $key == 1 || $key == 2 ||  $key == 3 || $key == 6 ) {
			continue;
		}
		if( $key == 4 ) { // Student
			$redirect = 'student-dashboard';
		}
		if( $key == 5 ) { // Teacher
			$redirect = 'teacher-dashboard';
		}
// 		if( $key == 6 ) { // Seller
// 			$redirect = 'seller-dashboard';
// 		}
		if( $key == 7 ) { // admin1
			$redirect = 'admin1-dashboard';
		}
		if( $key == 8 ) { // admin2
			$redirect = 'admin2-dashboard';
		}
		if( $key == 9 ) { // admin3
			$redirect = 'admin3-dashboard';
		}
		if( $key == 10 ) { // SUPER ADMIN
			$redirect = 'super-admin-dashboard';
		}
	}
	
	$query_count = count( $_GET );
	if( $query_count == 1 ) {
		$form_state['redirect'] = "$base_url/$redirect";
	}

}