<?php

/**
 * Implements hook_menu()
 */
function assign_teacher_menu() {
	
	$items['earnings-all-admin'] = array(
			'title' => 'Earnings all Admin',
			'page callback' => 'earnings_all_admin',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);
	
	$items['earnings-teacher'] = array(
			'title' => 'Earnings all Admin',
			'page callback' => 'earnings_teacher',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);
	
	return $items;
}

function earnings_all_admin(){
	$id = $_GET['id'];
	
	$num_updated = db_update('assign_teacher')
					->fields(array(
							'admin_status' => 'approved',
					))
					->condition('id', $id )
					->execute();
					
	drupal_set_message('Earning Approved');
	drupal_goto( 'earnings-all' );
}

function earnings_teacher(){
	$id = $_GET['id'];

	$num_updated = db_update('assign_teacher')
					->fields(array(
							'teacher_status' => 'approved',
					))
					->condition('id', $id )
					->execute();
		
	drupal_set_message('Earning Approved');
	drupal_goto( 'earnings' );
}

/**
 * Implements hook_views_api().
 */
function assign_teacher_views_api()
{
	return array(
			'api' => 3,
			'path' => drupal_get_path('module', 'assign_teacher') . '/views',
	);
}