<?php 
/**
 * Implements hook_menu()
 */
function quiz_do_lessons_menu() {
	$items['test-summary'] = array(
			'page callback' => 'test_summary',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
	);
	return $items;
}

function test_summary() {
	
	global $user;
		
	$num_updated = db_update('take_a_test')
						->fields(array(
								'validity' => 0,
						))
						->condition('time_of_test_purchased', REQUEST_TIME - 2592000, '<=') //2592000 for Seconds in 1 month
						->execute();
	
	$output = '';
	$output .= '<div class="take-a-test-wrapper">
			    <table>
			     <thead>
			       <tr>
			         <th>Test</th>
			         <th>Remaining Test(s)</th> 
			         <th>Date Of Purchased</th>
			       </tr>
			     </thead>';
	
	$results = db_select('take_a_test', 'tat')
					->fields('tat')
					->condition('uid', $user->uid, '=' )
					->condition('validity', 1, '=' )
					->condition('remaining_test', 0, '>' )
					->execute()
					->fetchAll();
	
	foreach( $results as $result ) {
		$test_type = $result->test_type;
		$remaining_test = $result->remaining_test;
		$time_of_test_purchased = format_date( $result->time_of_test_purchased, 'custom', t('j M Y', array(), array('context' => 'php date format')) );
		$output .= "<tr><td>$test_type</td><td>$remaining_test</td><td>$time_of_test_purchased</td></tr>";
	}
	
	$output .= '</table></div>';
	
	return $output;
	
}

/*
 * Implements hook_form_alter()
 */
function quiz_do_lessons_form_user_login_alter( &$form, &$form_state ) {

	$form['#submit'][] = 'quiz_do_lessons_user_login_submit';
}

/**
 * Additional handler for user_login form submit.
 */
function quiz_do_lessons_user_login_submit($form, &$form_state) {
	global $base_url;
	if( array_key_exists( 'arg', $_GET ) ) {
		$arg = $_GET['arg'];
		if( $arg == '181' ) {
			$form_state['redirect'] = "$base_url/node/181/take";
		} else if( $arg == '212' ) {
			$form_state['redirect'] = "$base_url/node/212/take";
		} else if( $arg == '184' ) {
			$form_state['redirect'] = "$base_url/node/184/take";
		} else if( $arg == '186' ) {
			$form_state['redirect'] = "$base_url/node/186/take";
		} else if( $arg == '183' ) {
			$form_state['redirect'] = "$base_url/node/183/take";
		}
	
	}
}

function quiz_do_lessons_form_commerce_checkout_form_complete_alter( &$form, &$form_state ) {
	
	global $base_url;
	global $user;
	$uid = $user->uid;
	
	//for student test	
	if( array_key_exists( 'redirect_to_test', $_SESSION ) ) {

		switch( $_SESSION['redirect_to_test'] ) {

			case 'node/181/take'://SAT
				$test_type = 'SAT';
				$remaining_test = 15;
				break;
					
			case 'node/212/take'://GMAT
				$test_type = 'GMAT';
				$remaining_test = 15;
				break;
					
			case 'node/186/take'://WAEC
				$test_type = 'WAEC';
				$remaining_test = 20;
				break;
					
			case 'node/184/take'://JAMB
				$test_type = 'JAMB';
				$remaining_test = 20;
				break;
					
			case 'node/183/take'://GRE
				$test_type = 'GRE';
				$remaining_test = 15;
				break;
		}
		
		$nid = db_insert('take_a_test')
					->fields(array(
							'uid' => $uid,
							'remaining_test' => $remaining_test,
							'test_type' => $test_type,
							'time_of_test_purchased' => REQUEST_TIME,
							'validity' => 1
					))
					->execute();
		$redirect_to_test = $_SESSION['redirect_to_test'];
		unset( $_SESSION['redirect_to_test'] );
		drupal_goto( "$base_url/$redirect_to_test" );
	}
		
}


